<?php

namespace Zerp\Twilio\Database\Seeders;

use App\Models\Notification;
use App\Models\NotificationTemplateLang;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Seeder;

class NotificationsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Model::unguard();

        $modules = [
            'general'                 => ['New User', 'New Sales Invoice', 'Sales Invoice Status Updated', 'New Proposal', 'Proposal Status Updated', 'Bank Transfer Payment Status Updated', 'New Purchase Invoice', 'New Warehouse'],
            'Account'                 => ['New Customer', 'New Vendor', 'New Revenue'],            
            'Contract'                => ['New Contract'],
            'Hrm'                     => ['New Monthly Payslip', 'New Award', 'New Event', 'Leave Approve/Reject', 'New Announcement', 'New Holidays'],
            'Lead'                    => ['New Lead', 'Lead to Deal Conversion', 'New Deal', 'Lead Moved', 'Deal Moved'],        
            'Taskly'                  => ['New Project', 'New Task', 'New Bug', 'New Milestone', 'Task Stage Updated', 'New Task Comment'],
            'ZoomMeeting'             => ['New Zoom Meeting'],
            'Timesheet'               => ['New Timesheet'],
        ];

        $defaultTemplate = [
            'New User'                    => [
                'variables' => '{"Company Name": "company_name","User Name": "user_name" }',
                'lang'      => [
                    'ar' => 'مستخدم جديد {user_name} تم تكوينه بواسطة {company_name}',
                    'da' => 'En ny bruger {user_name} er oprettet af {company_name}',
                    'de' => 'Ein neuer Benutzer {user_name} wurde erstellt von {company_name}',
                    'en' => 'A New User {user_name} has been created by {company_name}',
                    'es' => 'Un nuevo usuario {user_name} ha sido creado por {company_name}',
                    'fr' => 'Un nouvel utilisateur {user_name} a été créé par {company_name}',
                    'it' => 'Un Nuovo utente {user_name} è stato creato da {company_name}',
                    'ja' => '新規ユーザー {user_name} が {company_name} によって作成されました。',
                    'nl' => 'Een nieuwe gebruiker {user_name} is gemaakt door {company_name}',
                    'pl' => 'Nowy użytkownik {user_name} został utworzony przez {company_name}',
                    'ru' => 'Новый пользователь {user_name} создано в {company_name}',
                    'pt' => 'Um Novo Usuário {user_name} foi criado por {company_name}',
                ],
            ],
            'New Sales Invoice'           => [
                'variables' => '{"Sales Invoice Id" : "sales_invoice_id" , "Company Name":"company_name"}',
                'lang'      => [
                    'ar' => 'فاتورة مبيعات جديدة {sales_invoice_id} تكوين بواسطة {company_name}',
                    'da' => 'Ny salgsfaktura {sales_invoice_id} oprettet af {company_name}',
                    'de' => 'Neue Verkaufsrechnung {sales_invoice_id} erstellt von {company_name}',
                    'en' => 'New Sales Invoice {sales_invoice_id} created by {company_name}',
                    'es' => 'Nueva factura de ventas {sales_invoice_id} creada por {nombre_empresa}',
                    'fr' => 'Nouvelle facture de vente {sales_invoice_id} Créé par {company_name}',
                    'it' => 'Nuova Fattura di vendita {sales_invoice_id} creata da {company_name}',
                    'ja' => ' 新規販売請求 {sales_invoice_id} 作成者 {company_name}',
                    'nl' => 'Nieuwe verkoopfactuur {sales_invoice_id} gemaakt door {company_name}',
                    'pl' => 'Nowa faktura sprzedaży {sales_invoice_id} utworzone przez {company_name}',
                    'ru' => 'Новая накладная продаж {sales_invoice_id} кем создано {company_name}',
                    'pt' => 'Nova Fatura De Vendas {sales_invoice_id} criado por {company_name}',
                ],
            ],
            'Sales Invoice Status Updated' => [
                'variables' => '{"Company Name" : "company_name" }',
                'lang' => [
                    'ar' => 'تم تعديل حالة الفاتورة بواسطة {company_name}',
                    'da' => 'Fakturastatus opdateret af {company_name}',
                    'de' => 'Rechnungsstatus aktualisiert von {company_name}',
                    'en' => 'Invoice status updated by {company_name}',
                    'es' => 'Estado de factura actualizado por {company_name}',
                    'fr' => 'Etat de la facture mis à jour par {company_name}',
                    'it' => 'Stato della fattura aggiornato da {company_name}',
                    'ja' => '請求書ステータスの更新者 {company_name}',
                    'nl' => 'Factuurstatus bijgewerkt door {company_name}',
                    'pl' => 'Status faktury zaktualizowany przez {company_name}',
                    'ru' => 'Состояние счета-фактуры изменено {company_name}',
                    'pt' => 'Status da fatura atualizado por {company_name}',
                ],
            ],
            'New Proposal' => [
                'variables' => '{"company Name": "company_name"}',
                'lang' => [
                    'ar' => 'اقتراح جديد تم تكوينه بواسطة {company_name}',
                    'da' => 'Ny Forslag til oprettet af {company_name}',
                    'de' => 'Neuer Vorschlag erstellt von {company_name}',
                    'en' => 'New Proposal created by {company_name}',
                    'es' => 'Nueva propuesta creada por {company_name}',
                    'fr' => 'Nouvelle proposition créée par {company_name}',
                    'it' => 'Nuova Proposta creata da {company_name}',
                    'ja' => '作成者の新規提案 {company_name}',
                    'nl' => 'Nieuw voorstel gemaakt door {company_name}',
                    'pl' => 'Nowa propozycja utworzona przez {company_name}',
                    'ru' => 'Новое предложение, созданное {company_name}',
                    'pt' => 'Nova Proposta criada por {company_name}',
                ],
            ],
            'Proposal Status Updated' => [
                'variables' => '{"Company Name" : "company_name" }',
                'lang' => [
                    'ar' => 'تم تحديث حالة المقترح بواسطة {company_name}',
                    'da' => 'Forslag til status opdateret af {company_name}',
                    'de' => 'Vorschlag für Status aktualisiert von {company_name}',
                    'en' => 'Proposal status updated by {company_name}',
                    'es' => 'Estado de la propuesta actualizado por {company_name}',
                    'fr' => 'Etat de la proposition mis à jour par {company_name}',
                    'it' => 'Stato di proposta aggiornato da {company_name}',
                    'ja' => 'プロポーザル状況の更新者 {company_name}',
                    'nl' => 'Status van voorstel bijgewerkt door {company_name}',
                    'pl' => 'Status propozycji został zaktualizowany przez {company_name}',
                    'ru' => 'Состояние предложения обновлено {company_name}',
                    'pt' => 'Status da proposta atualizado por {company_name}',
                ],
            ],
            'Bank Transfer Payment Status Updated' => [
                'variables' => '{"Company Name" : "company_name" ,"Invoice Id": "invoice_id"}',
                'lang' => [
                    'ar' => 'تمت الموافقة على طلب التحويل المصرفي بواسطة {company_name} للفاتورة {invoice_id}',
                    'da' => 'Bankoverførselsanmodning godkendt af {company_name} for faktura {invoice_id}',
                    'de' => 'Bank-Transfer-Anfrage genehmigt von {company_name} für Rechnung {invoice_id}',
                    'en' => 'Bank Transfer Request Approved by {company_name} for invoice {invoice_id}',
                    'es' => 'Solicitud de transferencia bancaria aprobada por {company_name} para la factura {invoice_id}',
                    'fr' => 'Demande de transfert bancaire approuvée par {company_name} Pour la facture {invoice_id}',
                    'it' => 'Richiesta Di Trasferimento Bancario Approvata da {company_name} per fattura {invoice_id}',
                    'ja' => '銀行振替要求承認済み {company_name} 請求書の {invoice_id}',
                    'nl' => 'Aanvraag bankoverdracht goedgekeurd door {company_name} voor factuur {invoice_id}',
                    'pl' => 'Zlecenie przelewu bankowego zatwierdzone przez {company_name} dla faktury {invoice_id}',
                    'ru' => 'Заявка на банковский перевод, утвержденная {company_name} для накладной {invoice_id}',
                    'pt' => 'Pedido De Transferência Bancária Aprovado por {company_name} para fatura {invoice_id}',
                ],
            ],
            'New Customer' => [
                'variables' => '{"Company Name": "company_name"}',
                'lang' => [
                    'ar' => 'تم تكوين عميل جديد بواسطة {company_name}',
                    'da' => 'Ny kunde oprettet af {company_name}',
                    'de' => 'Neuer Kunde erstellt von {company_name}',
                    'en' => 'New Customer created by {company_name}',
                    'es' => 'Nuevo creado por creado por {company_name}',
                    'fr' => 'Nouveau client créé par {company_name}',
                    'it' => 'Nuovo Cliente creato da {company_name}',
                    'ja' => '新規顧客が作成者 {company_name}',
                    'nl' => 'Nieuwe klant gemaakt door {company_name}',
                    'pl' => 'Nowy klient utworzony przez {company_name}',
                    'ru' => 'Новый заказчик, созданный {company_name}',
                    'pt' => 'Novo Cliente criado por {company_name}',
                ],
            ],
            'New Bill' => [
                'variables' => '{"Company Name": "company_name" , "Bill Id" : "bill_id"}',
                'lang' => [
                    'ar' => 'مشروع قانون جديد {bill_id} تكوين بواسطة {company_name}',
                    'da' => 'Ny faktura {bill_id} oprettet af {company_name}',
                    'de' => 'Neue Bill {bill_id} erstellt von {company_name}',
                    'en' => 'New Bill {bill_id} created by {company_name}',
                    'es' => 'Nueva factura {bill_id} creada por {company_name}',
                    'fr' => 'Nouvelle facture {bill_id} créée par {company_name}',
                    'it' => 'Nuovo Bill {bill_id} creato da {company_name}',
                    'ja' => '新規請求書 {bill_id} の作成者 {company_name}',
                    'nl' => 'Nieuwe factuur {bill_id} gemaakt door {company_name}',
                    'pl' => 'Nowy rachunek {bill_id} utworzone przez {company_name}',
                    'ru' => 'Новый законопроект {bill_id} кем создано {company_name}',
                    'pt' => 'Novo Bill {bill_id} criado por {company_name}',
                ],
            ],
            'New Vendor' => [
                'variables' => '{"Company Name": "company_name"}',
                'lang' => [
                    'ar' => 'تم تكوين مورد جديد بواسطة {company_name}',
                    'da' => 'Ny leverandør oprettet af {company_name}',
                    'de' => 'Neuer Anbieter erstellt von {company_name}',
                    'en' => 'New Vendor created by {company_name}',
                    'es' => 'Nuevo proveedor creado por {company_name}',
                    'fr' => 'Nouveau fournisseur créé par {company_name}',
                    'it' => 'Nuovo Fornitore creato da {company_name}',
                    'ja' => '新規ベンダーの作成者 {company_name}',
                    'nl' => 'Nieuwe leverancier gemaakt door {company_name}',
                    'pl' => 'Nowy dostawca utworzony przez {company_name}',
                    'ru' => 'Новый поставщик, созданный {company_name}',
                    'pt' => 'Novo Fornecedor criado por {company_name}',
                ],
            ],
            'New Revenue' => [
                'variables' => '{"Company Name": "company_name" , "User Name" : "user_name" , "Amount": "amount"}',
                'lang' => [
                    'ar' => 'عائد جديد {amount} تم التكوين الى {user_name} بواسطة {company_name}',
                    'da' => 'Ny indtægt for {amount} oprettet for {user_name} af {company_name}',
                    'de' => 'Neuer Umsatz von {amount} erstellt für {user_name} von {company_name}',
                    'en' => 'New Revenue of {amount} created for {user_name} by {company_name}',
                    'es' => 'Nuevos ingresos de {amount} creados para {user_name} por {company_name}',
                    'fr' => 'Nouveau chiffre daffaires de {amount} créé pour {user_name} par {company_name}',
                    'it' => 'Nuove Entrate di {amount} create per {user_name} da {company_name}',
                    'ja' => '新規収益 {amount} 作成対象 {user_name} による {company_name}',
                    'nl' => 'Nieuwe ontvangsten van {amount} gemaakt voor {user_name} door {company_name}',
                    'pl' => 'Nowy przychód z {amount} utworzone dla {user_name} przez użytkownika {company_name}',
                    'ru' => 'Новый доход от {amount} создано для {user_name} по {company_name}',
                    'pt' => 'Nova Receita de {amount} criado para {user_name} por {company_name}',
                ],
            ],
            'New Payment' => [
                'variables' => '{"Vender Name" : "vender_name" , "Amount": "amount"}',
                'lang' => [
                    'ar' => 'دفعة جديدة {amount} تم التكوين الى {vender_name} بواسطة السداد',
                    'da' => 'Ny betaling af {amount} oprettet for {vender_name} efter betaling',
                    'de' => 'Neue Zahlung von {amount} erstellt für {vender_name} durch Zahlung',
                    'en' => 'New payment of {amount} created for {vender_name} by payment',
                    'es' => 'Se ha creado un nuevo pago de {amount} para {vender_name} por pago',
                    'fr' => 'Nouveau paiement de {amount} créé pour {vender_name} par paiement',
                    'it' => 'Nuovo pagamento di {amount} creato per {vender_name} a pagamento',
                    'ja' => '新規支払い {amount} 作成対象 {vender_name} 支払いによって',
                    'nl' => 'Nieuwe betaling van {amount} gemaakt voor {vender_name} door betaling',
                    'pl' => 'Nowa płatność {amount} utworzone dla {vender_name} Według płatności',
                    'ru' => 'Новая выплата {amount} создано для {vender_name} по платежным',
                    'pt' => 'Novo pagamento de {amount} criado para {vender_name} por pagamento',
                ],
            ],
            'New Contract'                => [
                'variables' => '{"Company Name": "company_name" , "Contract Number" : "contract_number"}',
                'lang'      => [
                    'ar' => 'عقد جديد {contract_number} تم التكوين بواسطة {company_name}',
                    'da' => 'Ny kontrakt {contract_number} Oprettet af {company_name}',
                    'de' => 'Neuer Vertrag {contract_number} Erstellt von {company_name}',
                    'en' => 'New Contract {contract_number} Created By {company_name}',
                    'es' => 'Se ha creado el nuevo contrato {contract_number} por {company_name}',
                    'fr' => 'Nouveau contrat {contract_number} Créé par {company_name}',
                    'it' => 'Nuovo Contratto {contract_number} Creato da {company_name}',
                    'ja' => '新規契約 {contract_number} 作成者 {company_name}',
                    'nl' => 'Nieuw contract {contract_number} Gemaakt door {company_name}',
                    'pl' => 'Nowa umowa {contract_number} Utworzone przez {company_name}',
                    'ru' => 'Новый договор {contract_number} Кем создано {company_name}',
                    'pt' => 'Novo Contrato {contract_number} Criado Por {company_name}',
                ],
            ],
            'New Monthly Payslip' => [
                'variables' => '{"Month": "month"}',
                'lang' => [
                    'ar' => 'صك الراتب الذي تم تكوينه من {month}',
                    'da' => 'udbetalinger genereret af {month}',
                    'de' => 'Payslip generiert von {month}',
                    'en' => 'payslip generated of {month}',
                    'es' => 'payslip generado de {month}',
                    'fr' => 'Bordereau de paiement généré {month}',
                    'it' => 'payslip generato di {month}',
                    'ja' => '生成された給与明細 {month}',
                    'nl' => 'payslip gegenereerd van {month}',
                    'pl' => 'Wygenerowano payslip {month}',
                    'ru' => 'Пауза, сгенерированная из {month}',
                    'pt' => 'payslip gerado de {month}',
                ],
            ],
            'New Award' => [
                'variables' => '{"Date": "date" , "User Name" : "user_name" , "Award Name" : "award_name"}',
                'lang' => [
                    'ar' => '{award_name} تم التكوين الى {user_name} من {date}',
                    'da' => '{award_name} oprettet for {user_name} fra {date}',
                    'de' => '{award_name} erstellt für {user_name} von {date}',
                    'en' => '{award_name} created for {user_name} from {date}',
                    'es' => '{award_name} creado para {user_name} desde {date}',
                    'fr' => '{award_name} Créé pour {user_name} à partir de {date}',
                    'it' => '{award_name} creato per {user_name} da {date}',
                    'ja' => '{award_name} 作成対象 {user_name} からの {date}',
                    'nl' => '{award_name} gemaakt voor {user_name} van {date}',
                    'pl' => '{award_name} utworzone dla {user_name} od {date}',
                    'ru' => '{award_name} создано для {user_name} от {date}',
                    'pt' => '{award_name} criado para {user_name} de {date}',
                ],
            ],
            'New Event' => [
                'variables' => '{"Branch Name": "branch_name" , "Start Date" : "start_date" , "End Date" : "end_date" ,"Event Name" : "event_name"}',
                'lang' => [
                    'ar' => '{event_name} للفرع {branch_name} من {start_date} الى {end_date}',
                    'da' => '{event_name} for gren {branch_name} fra {start_date} til {end_date}',
                    'de' => '{event_name} für Zweig {branch_name} von {start_date} bis {end_date}',
                    'en' => '{event_name} for branch {branch_name} from {start_date} to {end_date}',
                    'es' => '{event_name} para la rama {branch_name} de {start_date} a {end_date}',
                    'fr' => '{event_name} Pour la branche {branch_name} de {start_date} à {end_date}',
                    'it' => '{event_name} per il ramo {branch_name} da {start_date} a {end_date}',
                    'ja' => '{event_name} ブランチの {branch_name} からの {start_date} に対する {end_date}',
                    'nl' => '{event_name} voor vertakking {branch_name} van {start_date} tot {end_date}',
                    'pl' => '{event_name} dla gałęzi {branch_name} od {start_date} do {end_date}',
                    'ru' => '{event_name} для ветви {branch_name} от {start_date} в {end_date}',
                    'pt' => '{event_name} for branch {branch_name} de {start_date} para {end_date}',
                ],
            ],
            'Leave Approve/Reject' => [
                'variables' => '{"Status" : "status"}',
                'lang' => [
                    'ar' => 'لقد كانت رحلتك {status}',
                    'da' => 'Din orlov er blevet ... {status}',
                    'de' => 'Ihr Urlaub ist {status}',
                    'en' => 'Your leave has been {status}',
                    'es' => 'Su licencia ha sido {status}',
                    'fr' => 'Votre congé a été {status}',
                    'it' => 'Il tuo congedo è stato {status}',
                    'ja' => 'あなたの休暇は {status}',
                    'nl' => 'Uw verlof is {status}',
                    'pl' => 'Twój urlop był {status}',
                    'ru' => 'Ваш отпуск был {status}',
                    'pt' => 'Sua licença foi {status}',
                ],
            ],
            'New Announcement' => [
                'variables' => '{"Announcement Name" : "announcement_name" , "Branch Name" : "branch_name" , "Start Date" : "start_date" , "End Date" : "end_date"}',
                'lang' => [
                    'ar' => '{announcement_name} تم تكوين الاشعار للفرع {branch_name} من {start_date} الى {end_date}',
                    'da' => '{announcement_name} annoncering oprettet for gren {branch_name} fra {start_date} til {end_date}',
                    'de' => '{announcement_name} Ankündigung für Verzweigung erstellt {branch_name} von {start_date} bis {end_date}',
                    'en' => '{announcement_name} announcement created for branch {branch_name} from {start_date} to {end_date}',
                    'es' => '{announcement_name} anuncio creado para la rama {branch_name} de {start_date} a {end_date}',
                    'fr' => '{announcement_name} Annonce créée pour la branche {branch_name} à partir de {start_date} Vers {end_date}',
                    'it' => '{announcement_name} annuncio creato per il ramo {branch_name} da {start_date} a {end_date}',
                    'ja' => '{announcement_name} ブランチ用に作成された {branch_name} からの {start_date} に対する {end_date}',
                    'nl' => '{announcement_name} announcement gemaakt voor vertakking {branch_name} van {start_date} tot {end_date}',
                    'pl' => '{announcement_name} announcement utworzone dla gałęzi {branch_name} od {start_date} do {end_date}',
                    'ru' => '{announcement_name} объявление, созданное для ветви {branch_name} от {start_date} в {end_date}',
                    'pt' => '{announcement_name} anúncio criado para filial {branch_name} de {start_date} para {end_date}',
                ],
            ],
            'New Holidays' => [
                'variables' => '{"Name" : "name" , "Start Date" : "start_date" , "End Date" : "end_date"}',
                'lang' => [
                    'ar' => '{name} في {start_date} الى {end_date}',
                    'da' => '{name} om {start_date} til {end_date}',
                    'de' => '{name} on {start_date} bis {end_date}',
                    'en' => '{name} on {start_date} to {end_date}',
                    'es' => '{name} en {start_date} a {end_date}',
                    'fr' => '{name} Sur {start_date} à {end_date}',
                    'it' => '{name} su {start_date} a {end_date}',
                    'ja' => '{name} オン {start_date} に対する {end_date}',
                    'nl' => '{name} op {start_date} tot {end_date}',
                    'pl' => '{name} w dniu {start_date} do {end_date}',
                    'ru' => '{name} вн {start_date} в {end_date}',
                    'pt' => '{name} em {start_date} para {end_date}',
                ],
            ],
            'New Lead'                    => [
                'variables' => '{"Company Name" : "company_name"}',
                'lang'      => [
                    'ar' => 'دليل جديد تم تكوينه بواسطة {company_name}',
                    'da' => 'Nyt bly oprettet af {company_name}',
                    'de' => 'Neuer Lead erstellt von {company_name}',
                    'en' => 'New lead created by the {company_name}',
                    'es' => 'Nueva ventaja creada por el {company_name}',
                    'fr' => 'Nouveau lead créé par le {company_name}',
                    'it' => 'Nuovo lead creato dal {company_name}',
                    'ja' => '新規リードの作成者 {company_name}',
                    'nl' => 'Nieuwe leiding gemaakt door de {company_name}',
                    'pl' => 'Nowy ołów utworzony przez {company_name}',
                    'ru' => 'Новый руководитель, созданный {company_name}',
                    'pt' => 'Nova liderança criada pelo {company_name}',
                ],
            ],
            'Lead to Deal Conversion'     => [
                'variables' => '{"Name" : "name"}',
                'lang'      => [
                    'ar' => 'تم تحويل الصفقة من خلال الرصاص {name}',
                    'da' => 'Aftale er konverteret via bly {name}',
                    'de' => 'Durch Lead {name} konvertierte Transaktion',
                    'en' => 'Deal converted through lead {name}',
                    'es' => 'Acuerdo convertido a través del plomo {name}',
                    'fr' => 'Deal converti par le biais du plomb {name}',
                    'it' => 'Accordo convertito tramite lead {name}',
                    'ja' => 'リードを介して変換された取引 {name}',
                    'nl' => 'Deal geconverteerd door middel van lood {name}',
                    'pl' => 'Układ przekształcony przez ołów {name}',
                    'ru' => 'Сделка преобразована через ведущую роль {name}',
                    'pt' => 'Acordo convertido através de chumbo {name}',
                ],
            ],
            'New Deal'                    => [
                'variables' => '{"Company Name" : "company_name"}',
                'lang'      => [
                    'ar' => 'الصفقة الجديدة التي تم تكوينها بواسطة {company_name}',
                    'da' => 'Ny aftale oprettet af {company_name}',
                    'de' => 'Neuer Deal, der von {company_name} erstellt wurde',
                    'en' => 'New Deal created by the {company_name}',
                    'es' => 'Nuevo acuerdo creado por el {company_name}',
                    'fr' => 'Nouveau pacte créé par {company_name}',
                    'it' => 'Nuovo Deal creato dal {company_name}',
                    'ja' => '次のユーザーによって作成された新規取引 {company_name}',
                    'nl' => 'Nieuwe Deal gemaakt door de {company_name}',
                    'pl' => 'Nowa umowa utworzona przez {company_name}',
                    'ru' => 'Новая сделка, созданная {company_name}',
                    'pt' => 'Novo Acordo criado pelo {company_name}',
                ],
            ],
            'Lead Moved'                  => [
                'variables' => '{"Lead Name" : "lead_name", "Old Stage":"old_stage","New Stage":"new_stage"}',
                'lang'      => [
                    'ar' => '{lead_name} تم تغيير الحالة من {old_stage} الى {new_stage}',
                    'da' => '{lead_name} status ændret fra {old_stage} til {new_stage}',
                    'de' => '{lead_name} Status geändert von {old_stage} bis {new_stage}',
                    'en' => '{lead_name} status changed from {old_stage} to {new_stage}',
                    'es' => '{lead_name} estado cambiado de {old_stage} a {new_stage}',
                    'fr' => '{lead_name} Statut modifié par {old_stage} Vers {new_stage}',
                    'it' => '{lead_name} stato modificato da {old_stage} a {new_stage}',
                    'ja' => '{lead_name} 状況の変更元 {old_stage} に対する {new_stage}',
                    'nl' => '{lead_name} status gewijzigd van {old_stage} tot {new_stage}',
                    'pl' => '{lead_name} status zmieniony z {old_stage} do {new_stage}',
                    'ru' => '{lead_name} состояние изменено с {old_stage} в {new_stage}',
                    'pt' => '{lead_name} status alterado de {old_stage} para {new_stage}',
                ],
            ],
            'Deal Moved'                  => [
                'variables' => '{"Deal Name" : "deal_name", "Old Stage":"old_stage","New Stage":"new_stage"}',
                'lang'      => [
                    'ar' => '{deal_name} تم تغيير الحالة من {old_stage} الى {new_stage}',
                    'da' => '{deal_name} status ændret fra {old_stage} til {new_stage}',
                    'de' => '{deal_name} Status geändert von {old_stage} bis {new_stage}',
                    'en' => '{deal_name} status changed from {old_stage} to {new_stage}',
                    'es' => '{deal_name} estado cambiado de {old_stage} a {new_stage}',
                    'fr' => '{deal_name} Statut modifié par {old_stage} Vers {new_stage}',
                    'it' => '{deal_name} stato modificato da {old_stage} a {new_stage}',
                    'ja' => '{deal_name} 状況の変更元 {old_stage} に対する {new_stage}',
                    'nl' => '{deal_name} status gewijzigd van {old_stage} tot {new_stage}',
                    'pl' => '{deal_name} status zmieniony z {old_stage} do {new_stage}',
                    'ru' => '{deal_name} состояние изменено с {old_stage} в {new_stage}',
                    'pt' => '{deal_name} status alterado de {old_stage} para {new_stage}',
                ],
            ],
            'New Purchase Invoice'                => [
                'variables' => '{"Purchase Id" : "purchase_id", "Company Name" : "company_name"}',
                'lang'      => [
                    'ar' => 'شراء جديد {purchase_id} تكوين بواسطة الى {company_name}',
                    'da' => 'Nyt indkøb {purchase_id} oprettet af til {company_name}',
                    'de' => 'Neuer Kauf {purchase_id} erstellt von nach {company_name}',
                    'en' => 'New Purchase {purchase_id} created by to {company_name}',
                    'es' => 'Nueva compra {purchase_id} creada por {company_name}',
                    'fr' => 'Nouvel achat {purchase_id} Créé par pour {company_name}',
                    'it' => 'Nuovo Acquisto {purchase_id} creato da a {company_name}',
                    'ja' => '新規購入 {purchase_id} 作成者 {company_name}',
                    'nl' => 'Nieuwe aankoop {purchase_id} skabt af til {company_name}',
                    'pl' => 'Nowy zakup {purchase_id} utworzone przez {company_name}',
                    'ru' => 'Новая покупка {purchase_id} создано в {company_name}',
                    'pt' => 'Nova Compra {purchase_id} criado por para {company_name}',
                ],
            ],
            'New Warehouse'               => [
                'variables' => '{"Company Name": "company_name" , "Warehouse Name":"warehouse_name"}',
                'lang'      => [
                    'ar' => 'مخزن جديد {warehouse_name} تكوين بواسطة {company_name}',
                    'da' => 'Nyt lager {warehouse_name} oprettet af {company_name}',
                    'de' => 'Neues Lager {warehouse_name} erstellt von {company_name}',
                    'en' => 'New Warehouse {warehouse_name} created by {company_name}',
                    'es' => 'Nuevo almacén {warehouse_name} creado por {company_name}',
                    'fr' => 'Nouvel entrepôt {warehouse_name} Créé par {company_name}',
                    'it' => 'Nuovo Magazzino {warehouse_name} creato da {company_name}',
                    'ja' => '新規ウェアハウス {warehouse_name} 作成者 {company_name}',
                    'nl' => 'Nieuw magazijn {warehouse_name} gemaakt door {company_name}',
                    'pl' => 'Nowy magazyn {warehouse_name} utworzone przez {company_name}',
                    'ru' => 'Новый склад {warehouse_name} кем создано {company_name}',
                    'pt' => 'Novo Armazém {warehouse_name} criado por {company_name}',
                ],
            ],
            'New Project'                 => [
                'variables' => '{"Company Name" : "company_name" , "Project Name":"project_name"}',
                'lang'      => [
                    'ar' => '{project_name} تكوين بواسطة {company_name}',
                    'da' => '{project_name} oprettet af {company_name}',
                    'de' => '{project_name} erstellt von {company_name}',
                    'en' => '{project_name} created by {company_name}',
                    'es' => '{project_name} creado por {company_name}',
                    'fr' => '{project_name} Créé par {company_name}',
                    'it' => '{project_name} creato da {company_name}',
                    'ja' => '{project_name} 作成者 {company_name}',
                    'nl' => '{project_name} gemaakt door {company_name}',
                    'pl' => '{project_name} utworzone przez {company_name}',
                    'ru' => '{project_name} кем создано {company_name}',
                    'pt' => '{project_name} criado por {company_name}',
                ],
            ],
            'New Task'                    => [
                'variables' => '{"Company Name" : "company_name" , "Project Name":"project_name" , "Task Name":"task_name"}',
                'lang'      => [
                    'ar' => '{task_name} من {project_name} تكوين بواسطة {company_name}',
                    'da' => '{task_name} af {project_name} oprettet af {company_name}',
                    'de' => '{task_name} von {project_name} erstellt von {company_name}',
                    'en' => '{task_name} of {project_name} created by {company_name}',
                    'es' => '{task_name} de {project_name} creado por {company_name}',
                    'fr' => '{task_name} De {project_name} Créé par {company_name}',
                    'it' => '{task_name} di {project_name} creato da {company_name}',
                    'ja' => '{task_name} の {project_name} 作成者 {company_name}',
                    'nl' => '{task_name} van {project_name} gemaakt door {company_name}',
                    'pl' => '{task_name} z {project_name} utworzone przez {company_name}',
                    'ru' => '{task_name} из {project_name} кем создано {company_name}',
                    'pt' => '{task_name} de {project_name} criado por {company_name}',
                ],
            ],
            'New Bug'                     => [
                'variables' => '{"Company Name" : "company_name" , "Project Name":"project_name" , "Bug Name":"bug_name"}',
                'lang'      => [
                    'ar' => 'حشرة جديدة {bug_name} من {project_name} تكوين بواسطة {company_name}',
                    'da' => 'Ny boble {bug_name} af {project_name} oprettet af {company_name}',
                    'de' => 'Neuer Fehler {bug_name} von {project_name} erstellt von {company_name}',
                    'en' => 'New Bug {bug_name} of {project_name} created by {company_name}',
                    'es' => 'Se ha creado un nuevo error {bug_name} de {project_name} por {company_name}',
                    'fr' => 'Nouveau bug {bug_name} De {project_name} Créé par {company_name}',
                    'it' => 'Nuovo Bug {bug_name} di {project_name} creato da {company_name}',
                    'ja' => '新規バグ {bug_name} の {project_name} 作成者 {company_name}',
                    'nl' => 'Nieuwe bug {bug_name} van {project_name} gemaakt door {company_name}',
                    'pl' => 'Nowy błąd programu {bug_name} z {project_name} utworzone przez {company_name}',
                    'ru' => 'Новый дефект {bug_name} из {project_name} кем создано {company_name}',
                    'pt' => 'Novo Bug {bug_name} de {project_name} criado por {company_name}',
                ],
            ],
            'New Milestone'               => [
                'variables' => '{"Company Name": "company_name"}',
                'lang'      => [
                    'ar' => 'حدث مميز جديد تم تكوينه بواسطة {company_name}',
                    'da' => 'Ny Milepæl oprettet af {company_name}',
                    'de' => 'Neuer Meilenstein, der von der {company_name}',
                    'en' => 'New Milestone created by the {company_name}',
                    'es' => 'Nuevo hito creado por el {company_name}',
                    'fr' => 'Nouveau jalon créé par le {company_name}',
                    'it' => 'Nuovo Milestone creato dal {company_name}',
                    'ja' => '新規マイルストーンが作成されました {company_name}',
                    'nl' => 'Nieuwe mijlpaal gemaakt door de {company_name}',
                    'pl' => 'Nowy kamień milowy utworzony przez {company_name}',
                    'ru' => 'Новая веха, созданная {company_name}',
                    'pt' => 'Novo Marco criado pelo {company_name}',
                ],
            ],
            'Task Stage Updated'          => [
                'variables' => '{"Task Name": "task_name" , "Old Status":"old_status" , "New Status":"new_status"}',
                'lang'      => [
                    'ar' => '{task_name} تم تغيير الحالة من {old_status} الى {new_status}',
                    'da' => '{task_name} status ændret fra{old_status} til {new_status}',
                    'de' => '{task_name} Status geändert von {old_status} bis {new_status}',
                    'en' => '{task_name} status changed from {old_status} to {new_status}',
                    'es' => '{task_name} cambio de estado de {old_status} a {new_status}',
                    'fr' => '{task_name} Statut modifié par {old_status} Vers {new_status}',
                    'it' => '{task_name} stato modificato da {old_status} a {new_status}',
                    'ja' => '{task_name} 状況の変更元 {old_status} に対する {new_status}',
                    'nl' => '{task_name} status gewijzigd van {old_status} tot {new_status}',
                    'pl' => '{task_name} status zmieniony z {old_status} do {new_status}',
                    'ru' => '{task_name} состояние изменено с {old_status} в {new_status}',
                    'pt' => '{task_name} status alterado de {old_status} para {new_status}',
                ],
            ],
            'New Task Comment'            => [
                'variables' => '{"Task Name": "task_name"}',
                'lang'      => [
                    'ar' => 'اضافة تعقيب في {task_name}',
                    'da' => 'kommentar tilføjet i {task_name}',
                    'de' => 'Kommentar hinzugefügt in {task_name}',
                    'en' => 'comment added in {task_name}',
                    'es' => 'comentario añadido en {task_name}',
                    'fr' => 'Commentaire ajouté dans {task_name}',
                    'it' => 'commento aggiunto in {task_name}',
                    'ja' => 'コメントの追加 {task_name}',
                    'nl' => 'ccommentaar toegevoegd in {task_name}',
                    'pl' => 'komentarz dodany w {task_name}',
                    'ru' => 'комментарий добавлен в {task_name}',
                    'pt' => 'comentário incluído em {task_name}',
                ],
            ],
            'New Zoom Meeting'            => [
                'variables' => '{"User Name" : "user_name" , "Meeting Name":"meeting_name" , "Date":"date"}',
                'lang'      => [
                    'ar' => '{meeting_name} تم التكوين الى {user_name} من {date}',
                    'da' => '{meeting_name} oprettet for {user_name} fra {date}',
                    'de' => '{meeting_name} erstellt für {user_name} von {date}',
                    'en' => '{meeting_name} created for {user_name} from {date}',
                    'es' => '{meeting_name} creado para {user_name} desde {date}',
                    'fr' => '{meeting_name} Créé pour {user_name} à partir de {date}',
                    'it' => '{meeting_name} creato per {user_name} da {date}',
                    'ja' => '{meeting_name} 作成対象 {user_name} からの {date}',
                    'nl' => '{meeting_name} gemaakt voor {user_name} from {date}',
                    'pl' => '{meeting_name} utworzone dla {user_name} od {date}',
                    'ru' => '{meeting_name} создано для {user_name} от {date}',
                    'pt' => '{meeting_name} criado para {user_name} de {date}',
                ],
            ],
            'New Timesheet' => [
                'variables' => '{"Company Name" : "company_name" , "User Name" : "user_name" , "Type" : "type"}',
                'lang' => [
                    'ar' => 'تم إنشاء جدول زمني جديد ل {user_name} في {type} بواسطة {company_name}',
                    'da' => 'Der oprettes en ny timeseddel til {user_name} i {type} ved {company_name}',
                    'de' => 'Ein neuer Stundenzettel wird erstellt für {user_name} In {type} von {company_name}',
                    'en' => 'A New Timesheet is created for {user_name} in {type} by {company_name}',
                    'es' => '{company_name} crea una nueva hoja de horas para {user_name} en {type}',
                    'fr' => 'Une nouvelle feuille de temps est créée pour {user_name} dans {type} par {company_name}',
                    'it' => 'Viene creata una nuova scheda attività per {user_name} nella {type} di {company_name}',
                    'ja' => '新しいタイムシートが作成されます {user_name} で {type} による {company_name}',
                    'nl' => 'Er wordt een nieuwe urenstaat aangemaakt {user_name} op {type} door {company_name}',
                    'pl' => 'Utworzono nowy grafik dla {user_name} W {type} przez {company_name}',
                    'ru' => 'Новое расписание создано для {user_name} в {type} к {company_name}',
                    'pt' => 'Um novo quadro de horários é criado para {user_name} em {type} por {company_name}',
                ],
            ],
        ];

        foreach ($modules as $module_name => $actions) {
            foreach ($actions as $action) {
                $ntfy = Notification::where('action', $action)->where('type', 'Twilio')->where('module', $module_name)->count();

                if ($ntfy == 0) {
                    $new         = new Notification();
                    $new->action = $action;
                    $new->status = 'on';
                    $new->module = $module_name;
                    $new->type   = 'Twilio';
                    $new->save();

                    foreach ($defaultTemplate[$action]['lang'] as $lang => $content) {
                        NotificationTemplateLang::create([
                            'parent_id' => $new->id,
                            'lang'      => $lang,
                            'module'    => $new->module,
                            'variables' => $defaultTemplate[$action]['variables'],
                            'content'   => $content,
                        ]);
                    }
                }
            }
        }
    }
}
